{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Model Version",
   "type": "stat",
   "targets": [
    {
     "expr": "version{job=\"model_evaluation\"}"
    }
   ]
  },
  {
   "title": "Model Creation Timestamp",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "creation_timestamp{job=\"model_evaluation\"}"
    }
   ]
  },
  {
   "title": "Model Accuracy",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit", "label": "Accuracy" }
   ],
   "targets": [
    {
     "expr": "model_accuracy{job=\"model_evaluation\"}",
     "legendFormat": "{{model_name}} v{{model_version}}"
    }
   ]
  },
  {
   "title": "Model Loss",
   "type": "graph",
   "yaxes": [
    { "format": "none", "label": "Loss" }
   ],
   "targets": [
    {
     "expr": "model_loss{job=\"model_evaluation\"}",
     "legendFormat": "{{model_name}} v{{model_version}}"
    }
   ]
  },
  {
   "title": "Request per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s])) by (le, handler))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s])) by (le, handler))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{le=\"0.1\"}[1m]) \n/ ignoring (le) increase(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}