global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "app"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    dns_sd_configs:
      - names: ["api"]
        port: 8086
        type: A
        refresh_interval: 5s

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
