# @package _global_

defaults:
  - data: mnist
  - model: mnist
  - logger: mlflow
  - optimizer: ball
  - scheduler: reduce_lr_on_plateau
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - _self_

logger:
  mlflow:
    experiment_name: "eval"

task_name: "eval"

tags: ["mnist"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
